const reduced = window.matchMedia('(prefers-reduced-motion: reduce)');
const menuButton = document.querySelector('#menu-toggle');
const menu = document.querySelector('#menu');
function closeMenu(){menu.hidden=true;menuButton.setAttribute('aria-expanded','false');}
menuButton.addEventListener('click',()=>{const open=menu.hidden;menu.hidden=!open;menuButton.setAttribute('aria-expanded',String(open));});
menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
document.addEventListener('click',e=>{if(!menu.hidden&&!menu.contains(e.target)&&!menuButton.contains(e.target))closeMenu();});
if(!reduced.matches&&'IntersectionObserver' in window){document.documentElement.classList.add('motion-ready');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));}
const story=document.querySelector('.bottle-story'), bottle=document.querySelector('.story-bottle'), statement=document.querySelector('.statement'), featured=document.querySelector('.featured'), featuredBottle=featured.querySelector('img'), cards=[...document.querySelectorAll('.photo-wrap img')];
const clamp=(v,min=0,max=1)=>Math.min(max,Math.max(min,v));
let scheduled=false;
function animate(){scheduled=false;const mobile=window.innerWidth<=700;if(reduced.matches){bottle.style.transform='';featuredBottle.style.transform='';statement.querySelector('h2').style.opacity='';return;}const r=story.getBoundingClientRect(),h=window.innerHeight;const stage=document.querySelector('.bottle-stage'),hero=document.querySelector('.hero'),notes=document.querySelector('.notes');const stop=hero.offsetHeight+Math.max(0,(notes.offsetHeight-stage.offsetHeight)/2);const p=clamp(-r.top/hero.offsetHeight);stage.style.top=mobile?'65px':Math.min(Math.max(0,-r.top+30),stop)+'px';stage.style.transform=mobile?'translate3d(0,'+((hero.offsetHeight-40)*p)+'px,0)':'';if(!mobile){bottle.style.transform=`translateX(${-window.innerWidth*.255*p}px) rotate(${13-31*p}deg) scale(${1-.05*p})`;}else bottle.style.transform='rotate('+(12-36*p)+'deg) scale('+(1-.12*p)+')';const sr=statement.getBoundingClientRect();if(sr.bottom>0&&sr.top<h){const progress=(h-sr.top)/(h+sr.height);statement.querySelector('h2').style.opacity=String(.25+.75*Math.sin(clamp(progress)*Math.PI));}cards.forEach(img=>{const cr=img.parentElement.getBoundingClientRect();if(cr.bottom>0&&cr.top<h)img.style.transform=`translateY(${-clamp((h-cr.top)/(h+cr.height))*30}px)`;});const fr=featured.getBoundingClientRect();if(fr.bottom>0&&fr.top<h){const fp=clamp((h-fr.top)/(h+fr.height));featuredBottle.style.transform=`translate(-50%,${(1-fp)*95}px) rotate(${-12+fp*8}deg)`;}}
function requestAnimation(){if(!scheduled){scheduled=true;window.requestAnimationFrame(animate);}}window.addEventListener('scroll',requestAnimation,{passive:true});window.addEventListener('resize',requestAnimation);reduced.addEventListener('change',()=>{if(reduced.matches)document.documentElement.classList.remove('motion-ready');requestAnimation();});animate();
const wines={classic:{label:'A COLEÇÃO ’61 / BRANCO DE UVAS BRANCAS',title:'Cuvée 61',copy:'Cítricos luminosos, pera fresca e a delicada riqueza do brioche. Borbulhas finas conduzem a um final fresco e mineral. Uma companhia elegante para ostras, peixes delicados e tardes sem pressa.',details:'Chardonnay · Brut · 750 ml · Servir a 8–10°C'},rose:{label:'A COLEÇÃO ’61 / ROSÉ',title:'Rosé 61',copy:'Morango silvestre, um toque de pétalas de rosa e uma vibrante nota cítrica. Delicado na cor, expressivo no caráter. Aprecie com salmão, pratos frescos de verão ou queijos macios.',details:'Rosé · Extra Brut · 750 ml · Servir a 8–10°C'},reserve:{label:'A COLEÇÃO ’61 / PRESTIGE',title:'Reserva 61',copy:'Uma expressão mais profunda da nossa filosofia paciente. Frutas maduras encontram amêndoas tostadas e um final longo e complexo. Um vinho para pratos marcantes e ocasiões que merecem ser lembradas.',details:'Cuvée de Prestígio · Brut · 750 ml · Servir a 10–12°C'}};
const dialog=document.querySelector('#wine-dialog');function showInfo(info){document.querySelector('#dialog-label').textContent=info.label;document.querySelector('#dialog-title').textContent=info.title;document.querySelector('#dialog-copy').textContent=info.copy;document.querySelector('#dialog-details').textContent=info.details;dialog.showModal();}
document.querySelectorAll('[data-wine]').forEach(b=>b.addEventListener('click',()=>showInfo(wines[b.dataset.wine])));document.querySelector('#discover').addEventListener('click',()=>showInfo({label:'A PROPRIEDADE / A ESSÊNCIA DO LUGAR',title:'Entre na nossa história.',copy:'Comece entre as videiras, acompanhe o vinho até a adega e termine com uma degustação guiada da coleção ’61. Descubra o vale sem pressa, pelas pessoas e pelos lugares que dão forma aos seus vinhos.',details:'Passeio pela propriedade · Visita à adega · Degustação guiada. As reservas estarão disponíveis quando os dados de contato da vinícola forem adicionados.'}));dialog.querySelectorAll('.dialog-close,.dialog-done').forEach(b=>b.addEventListener('click',()=>dialog.close()));dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();});





